"use client";

import { createContext, useContext, useEffect, useState } from "react";

type Language = "en" | "hi";

type LanguageContextType = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const translations = {
  en: {
  "navbar.home": "Home",
  "navbar.about": "About",
  "navbar.features": "Features",
  "navbar.dashboard": "Dashboard",
  "navbar.faq": "FAQ",
  "navbar.contact": "Contact",
  "navbar.login": "Login",
"navbar.farmerLogin": "Farmer Login",
"navbar.buyerLogin": "Buyer Login",
"navbar.registerFarmer": "Register as Farmer",
"navbar.registerBuyer": "Register as Buyer",
"hero.badge": "AI-Powered Demand-Driven Farming",
"hero.titleStart": "Why grow, without knowing",
"hero.titleHighlight": "who will buy?",
"hero.description": "An AI-powered demand-driven farming platform connecting farmers directly with buyers through transparent agreements, trust-based transactions, and demand-driven cultivation.",
"hero.farmerButton": "Farmer Login / Register",
"hero.buyerButton": "Buyer Login / Register",
"hero.farmers": "Farmers",
"hero.buyers": "Buyers",
"hero.agreements": "Agreements",
"hero.demandForecast": "Demand Forecast",
"hero.verifiedBuyer": "Verified Buyer",
"hero.contractReady": "Contract Ready",
"why.eyebrow": "Why KrishiSetu",
"why.title": "Farming, reimagined with trust and intelligence",
"why.description": "Everything you need to grow with confidence and sell with certainty",

"why.demand.title": "Demand-Driven Farming",
"why.demand.description": "Farmers grow based on real market demand rather than uncertainty.",

"why.connection.title": "Direct Farmer-Buyer Connection",
"why.connection.description": "Reduce dependency on middlemen and keep more of the value.",

"why.agreements.title": "Smart Digital Agreements",
"why.agreements.description": "Transparent contracts between farmers and buyers.",

"why.trust.title": "Trust & Reputation System",
"why.trust.description": "Reliable transactions backed by reputation badges.",
"how.eyebrow": "How It Works",
"how.title": "From requirement to delivery in five steps",
"how.description": "A clear, transparent journey for both farmers and buyers.",

"how.step1": "Buyer Posts Requirement",
"how.step2": "Farmer Accepts Contract",
"how.step3": "Agreement Generated",
"how.step4": "Cultivation & Monitoring",
"how.step5": "Delivery & Payment",
"impact.eyebrow": "Our Impact",
"impact.title": "Real change, measured in trust and income",

"impact.waste": "Reduced Crop Wastage",
"impact.income": "Increased Farmer Income",
"impact.market": "Better Market Access",
"impact.transactions": "Transparent Transactions",
"trust.eyebrow": "Trust & Reputation",
"trust.title": "Earn trust, unlock opportunity",
"trust.description": "Badges are earned through successful agreements, timely deliveries, quality compliance, and positive transaction history.",

"trust.bronze": "Bronze Badge",
"trust.silver": "Silver Badge",
"trust.gold": "Gold Badge",
"trust.platinum": "Platinum Badge",

"trust.verifiedUser": "Verified User",
"trust.reliablePartner": "Reliable Partner",
"trust.highlyTrusted": "Highly Trusted",
"trust.eliteMember": "Elite Member",
"testimonials.eyebrow": "Testimonials",
"testimonials.title": "Trusted by farmers and buyers alike",

"testimonials.ramesh.role": "Farmer, Maharashtra",
"testimonials.ramesh.quote": "I now grow only what buyers actually need. My income is steadier and I waste far less of my harvest.",

"testimonials.lakshmi.role": "Farmer, Telangana",
"testimonials.lakshmi.quote": "The digital agreements gave me confidence. Payments arrive on time and there are no middlemen taking a cut.",

"testimonials.anand.role": "Buyer, Delhi",
"testimonials.anand.quote": "Posting a requirement and getting matched with verified farmers has made our sourcing reliable and transparent.",

"testimonials.meera.role": "Bulk Buyer, Gujarat",
"testimonials.meera.quote": "The reputation badges help us pick trustworthy partners quickly. Quality and delivery have been consistent.",
"financial.eyebrow": "Financial Support",
"financial.title": "Funding and protection that grows with you",
"financial.description": "Access the financial tools that keep farming sustainable and secure.",

"financial.banks.title": "Banks & Credit Access",
"financial.banks.description": "Connect with lending partners for timely agricultural credit.",

"financial.insurance.title": "Crop Insurance",
"financial.insurance.description": "Protect your harvest against weather and market risks.",

"financial.schemes.title": "Government Schemes",
"financial.schemes.description": "Discover and apply for relevant subsidies and schemes.",

"financial.literacy.title": "Financial Literacy",
"financial.literacy.description": "Learn smart money management built for farming cycles.",

"fpo.eyebrow": "FPO & Community",
"fpo.title": "Connect Through Farmer Communities",
"fpo.description": "Stronger together — collaborate, negotiate and grow as one.",

"fpo.organizations.title": "Farmer Producer Organizations",
"fpo.organizations.description": "Join verified FPOs and grow together as a collective.",

"fpo.selling.title": "Collective Selling",
"fpo.selling.description": "Pool produce to access larger buyers and better prices.",

"fpo.negotiation.title": "Better Negotiation Power",
"fpo.negotiation.description": "Negotiate stronger terms with combined volume and trust.",

"fpo.community.title": "Community Support",
"fpo.community.description": "Share knowledge, resources and support across the network.",

"cta.title": "Join the Future of Agriculture",
"cta.description": "Whether you're a farmer or a buyer, KrishiSetu helps you build reliable and profitable partnerships.",
"cta.farmer": "Join as Farmer",
"cta.buyer": "Join as Buyer",

"footer.description": "An AI-powered demand-driven farming platform connecting farmers directly with buyers through transparent, trust-based agreements.",

"footer.company": "Company",
"footer.portals": "Portals",
"footer.followUs": "Follow Us",

"footer.about": "About",
"footer.features": "Features",
"footer.contact": "Contact",
"footer.faq": "FAQ",

"footer.farmerLogin": "Farmer Login",
"footer.farmerRegister": "Farmer Register",
"footer.buyerLogin": "Buyer Login",
"footer.buyerRegister": "Buyer Register",

"footer.facebook": "Facebook",
"footer.twitter": "Twitter",
"footer.whatsapp": "WhatsApp",
"footer.telegram": "Telegram",

"footer.rights": "All rights reserved.",

"languages.eyebrow": "Multi-Language Support",
"languages.title": "Farming Speaks Many Languages",
"languages.description": "Use KrishiSetu comfortably in the language you know best.",

"ai.eyebrow": "AI Intelligence",
"ai.title": "AI-Powered Farming Intelligence",
"ai.description": "Smarter decisions, from seed to sale, powered by data.",

"ai.cropRecommendation": "Crop Recommendation",
"ai.cropRecommendationDesc": "AI suggests the most profitable crops based on soil, season and demand.",

"ai.demandForecasting": "Demand Forecasting",
"ai.demandForecastingDesc": "Predict upcoming market demand so you plant exactly what sells.",

"ai.marketTrend": "Market Trend Analysis",
"ai.marketTrendDesc": "Track price movements and trends across regions in real time.",

"ai.profitEstimation": "Profit Estimation",
"ai.profitEstimationDesc": "Estimate returns before you sow with data-backed projections.",

"buyerCta.forBuyers": "For Buyers",
"buyerCta.title": "Looking For Specific Crops?",
"buyerCta.description": "Need flowers, fruits, vegetables, grains, or bulk agricultural produce? Log in to post your requirement and get direct supplies.",
"buyerCta.login": "Login to Post Requirement",
"buyerCta.footer": "Be the first buyer to create demand on KrishiSetu.",

"marketplace.title": "Buyer Requirements Marketplace",
"marketplace.subtitle": "Browse and respond to bulk crop purchase requests from verified buyers",
"marketplace.searchPlaceholder": "Search by crop name or company...",
"marketplace.all": "All",
"marketplace.vegetables": "Vegetables",
"marketplace.grains": "Grains",
"marketplace.fruits": "Fruits",
"marketplace.pulses": "Pulses",
"marketplace.filters": "Filters",
"marketplace.advancedFilters": "Advanced Filters",
"marketplace.minimumPrice": "Minimum Price (₹)",
"marketplace.pricePlaceholder": "e.g., 1500",
"marketplace.locationRadius": "Location Radius (km)",
"marketplace.radiusPlaceholder": "e.g., 50",
"marketplace.resetFilters": "Reset Filters",
"marketplace.fetchingRequirements": "Fetching live requirements...",
"marketplace.showing": "Showing",
"marketplace.requirement": "requirement",
"marketplace.requirements": "requirements",
"marketplace.verifiedBuyer": "Verified buyer",
"marketplace.requiredCrop": "Required Crop",
"marketplace.qualityGrade": "Quality Grade",
"marketplace.expectedPrice": "Expected Price",
"marketplace.deliveryLocation": "Delivery Location",
"marketplace.requiredBy": "Required By",
"marketplace.sendSupplyProposal": "Send Supply Proposal",
"marketplace.noRequirements": "No requirements found",
"marketplace.adjustSearch": "Try adjusting your search or filters to find more opportunities",
"marketplace.proposalSent": "Proposal sent to",
"marketplace.contactedShortly": "You will be contacted shortly.",
"marketplace.failedToLoad": "Failed to load requirements.",

"chat.myChats": "My Chats",
"chat.searchContacts": "Search contacts...",
"chat.activeNow": "Active now",
"chat.typeMessage": "Type your message here...",
"chat.attachFile": "Attach file",
"chat.sendMessage": "Send message",
"chat.selectConversation": "Select a conversation to start chatting",

"cropCard.acres": "Acres",
"cropCard.growthStage": "Growth Stage",
"cropCard.estimatedHarvest": "Est. Harvest",
"cropCard.healthy": "Healthy",
"cropCard.excellent": "Excellent",
"cropCard.needsAttention": "Needs Attention",

"cropRequirement.backToDashboard": "Back to Dashboard",
"cropRequirement.title": "Post New Crop Requirement",
"cropRequirement.subtitle": "Specify your crop requirements to receive competitive direct supply proposals from verified farmers.",
"cropRequirement.cropName": "Crop Name",
"cropRequirement.cropNamePlaceholder": "Enter crop name (e.g. Wheat, Tomato)...",
"cropRequirement.qualityGrade": "Quality/Grade Required",
"cropRequirement.selectGrade": "Select grade (optional)...",
"cropRequirement.gradeA": "Grade A (Premium)",
"cropRequirement.gradeB": "Grade B (Standard)",
"cropRequirement.organicCertified": "Organic Certified",
"cropRequirement.quantityNeeded": "Quantity Needed",
"cropRequirement.enterQuantity": "Enter quantity",
"cropRequirement.targetPrice": "Target Price (Total / Expected)",
"cropRequirement.deliveryDeadline": "Delivery Deadline",
"cropRequirement.deliveryLocation": "Delivery Location",
"cropRequirement.locationPlaceholder": "e.g., Indore, Delhi Mandi",
"cropRequirement.additionalTerms": "Additional Contract Terms",
"cropRequirement.optional": "Optional",
"cropRequirement.termsPlaceholder": "e.g., Moisture levels max 12%, Premium packaging required...",
"cropRequirement.publish": "Publish Procurement Demand →",
"cropRequirement.publishing": "Publishing...",
"cropRequirement.publishedSuccess": "Your procurement requirement has been published successfully! Redirecting...",
"cropRequirement.verifiedNetwork": "100% Verified Farmer Network Match",
"cropRequirement.mandiPricing": "Government Mandi Pricing Reference Compliant",
"cropRequirement.predictorAI": "KrishiSetu Predictor AI",
"cropRequirement.demandScore": "Demand Score",
"cropRequirement.highMarketDemand": "High Market Demand",
"cropRequirement.availableFarmers": "Available Farmers",
"cropRequirement.estimatedResponses": "Est. Responses",
"cropRequirement.suggestedPrice": "Suggested Price",
"cropRequirement.priceBelowAverage": "Your current input of",
"cropRequirement.belowClusterAverage": "is below the current micro-cluster average.",
"cropRequirement.typeTomato": "Type",
"cropRequirement.inCropName": "in Crop Name to simulate live AI procurement response matching.",
"cropRequirement.supportModule": "💡 Procurement Decisions Support Module Active",
"cropRequirement.noAuthToken": "No authentication token found. Please login as Buyer before posting requirements.",
"cropRequirement.sessionExpired": "Session expired. Please login again as Buyer.",
"cropRequirement.accessDenied": "Access Denied: Only Buyers can post requirements.",
"cropRequirement.failedToSubmit": "Failed to submit requirement.",
"cropRequirement.cropRequired": "Crop selection is required",
"cropRequirement.gradeRequired": "Quality/grade selection is required",
"cropRequirement.validQuantity": "Valid quantity is required",
"cropRequirement.validPrice": "Valid target price is required",
"cropRequirement.dateRequired": "Delivery date is required",
"cropRequirement.locationRequired": "Delivery location is required",

"cropsHeader.title": "My Crops Inventory",
"cropsHeader.subtitle": "Manage and monitor your organic crops",
"cropsHeader.searchPlaceholder": "Search crops...",
"cropsHeader.addNewCrop": "Add New Crop",

"farmerActivity.recentActivity": "Recent Activity",
"farmerActivity.contractCompleted": "Contract Completed",
"farmerActivity.soldWheat": "Sold Wheat to FreshMart Pvt Ltd",
"farmerActivity.today": "Today",
"farmerActivity.paymentReceived": "Payment Received",
"farmerActivity.paymentCredited": "$25,000 credited successfully",
"farmerActivity.twoDaysAgo": "2 days ago",
"farmerActivity.newCropListed": "New Crop Listed",
"farmerActivity.tomatoAdded": "Tomato added for sale",
"farmerActivity.oneWeekAgo": "1 week ago",

"farmerCrops.title": "Crops I Grow",
"farmerCrops.addCrop": "Add Crop",
"farmerCrops.rabiSeason": "Rabi Season",
"farmerCrops.kharifSeason": "Kharif Season",
"farmerCrops.winterCrop": "Winter Crop",
"farmerCrops.allSeason": "All Season",
"farmerCrops.winter": "Winter",
"farmerCrops.active": "Active",
"farmerCrops.available": "Available",
"farmerCrops.listed": "Listed",
"farmerCrops.addNewCrop": "Add New Crop",
"farmerCrops.cropName": "Crop Name",
"farmerCrops.season": "Season",
"farmerCrops.landArea": "Land Area (Acres)",
"farmerCrops.expectedYield": "Expected Yield",
"farmerCrops.saveCrop": "Save Crop",
"farmerCrops.cancel": "Cancel",

"farmerDocuments.paymentSummary": "Payment Summary",
"farmerDocuments.walletBalance": "Wallet Balance",
"farmerDocuments.pendingPayments": "Pending Payments",
"farmerDocuments.totalEarnings": "Total Earnings",
"farmerDocuments.documents": "Documents",
"farmerDocuments.aadhaarCard": "Aadhaar Card",
"farmerDocuments.landRecord": "Land Record",
"farmerDocuments.bankPassbook": "Bank Passbook",
"farmerDocuments.verified": "Verified",

"addCropModal.title": "Add New Crop",
"addCropModal.cropName": "Crop Name",
"addCropModal.selectCrop": "Select a crop...",
"addCropModal.other": "Other",
"addCropModal.customCropName": "Enter Custom Crop Name",
"addCropModal.customCropPlaceholder": "e.g. Mustard / Sugarcane",
"addCropModal.landArea": "Land Area (Acres)",
"addCropModal.landAreaPlaceholder": "e.g. 2.5",
"addCropModal.harvestDate": "Estimated Harvest Date",
"addCropModal.cancel": "Cancel",
"addCropModal.saving": "Saving...",
"addCropModal.addCrop": "Add Crop",
"addCropModal.organicTomatoes": "Organic Tomatoes",
"addCropModal.basmatiRice": "Basmati Rice",
"addCropModal.redOnions": "Red Onions",
"addCropModal.greenChillies": "Green Chillies",
"addCropModal.wheat": "Wheat",
"addCropModal.potatoes": "Potatoes",

"farmerStats.activeContracts": "Active Contracts",
"farmerStats.currentlyRunning": "Currently running",
"farmerStats.completedContracts": "Completed Contracts",
"farmerStats.successfullyDelivered": "Successfully delivered",
"farmerStats.totalEarnings": "Total Earnings",
"farmerStats.lifetimeIncome": "Lifetime income",
"farmerStats.buyerRating": "Buyer Rating",
"farmerStats.basedOnReviews": "Based on reviews",
"farmerStats.connectedBuyers": "Connected Buyers",
"farmerStats.trustedPartners": "Trusted partners",

"logoutModal.title": "Are you sure you want to logout?",
"logoutModal.description": "You will need to enter your credentials again to access your KrishiSetu dashboard panels.",
"logoutModal.cancel": "Cancel",
"logoutModal.confirm": "Yes, Logout",

"aboutHero.eyebrow": "About KrishiSetu",
"aboutHero.title": "Connecting Farmers with Better Opportunities",
"aboutHero.description": "Building a transparent and trusted agricultural ecosystem.",

"farmerTabs.overview": "Overview",
"farmerTabs.crops": "Crops",
"farmerTabs.activity": "Activity",
"farmerTabs.documents": "Documents",

"farmerHero.verifiedFarmer": "Verified Farmer",
"farmerHero.editProfile": "Edit Profile",
"farmerHero.memberSince": "Member Since",
"farmerHero.experience": "Experience",
"farmerHero.landOwned": "Land Owned",
"farmerHero.trustScore": "Trust Score",
"farmerHero.outOf": "out of 100",
"farmerHero.goldTrustedFarmer": "🏅 Gold Trusted Farmer",
"farmerHero.trustedBy": "Trusted by verified buyers on KrishiSetu",
"farmerHero.editFarmerProfile": "Edit Farmer Profile",
"farmerHero.farmerName": "Farmer Name",
"farmerHero.location": "Location",
"farmerHero.waterSource": "Water Source",
"farmerHero.saveChanges": "Save Changes",
"farmerHero.cancel": "Cancel",

"farmerOverview.aboutMe": "About Me",
"farmerOverview.description": "I am a dedicated farmer from Sehore, Madhya Pradesh. I grow high-quality crops using modern farming techniques and believe in long-term partnerships with buyers.",
"farmerOverview.mobile": "Mobile",
"farmerOverview.email": "Email",
"farmerOverview.address": "Address",
"farmerOverview.landDetails": "Land Details",
"farmerOverview.totalLand": "Total Land",
"farmerOverview.soilType": "Soil Type",
"farmerOverview.waterSource": "Water Source",
"farmerOverview.organicFarming": "Organic Farming",
"farmerOverview.yes": "Yes",

"farmerSidebar.dashboard": "Dashboard",
"farmerSidebar.myCrops": "My Crops",
"farmerSidebar.myContracts": "My Contracts",
"farmerSidebar.buyerRequirements": "Buyer Requirements",
"farmerSidebar.incomingRequests": "Incoming Requests",
"farmerSidebar.aiAnalytics": "AI Analytics",
"farmerSidebar.messages": "Messages",
"farmerSidebar.profile": "Profile",
"farmerSidebar.logout": "Logout",
 
"about.story": "Our Story",
"about.title": "Empowering Farmers, Transforming Agriculture",
"about.description": "KrishiSetu bridges the gap between farmers and buyers through AI-powered demand-driven farming, ensuring fair prices and sustainable practices.",

"about.mission": "Our Mission",
"about.missionParagraph1": "We believe every farmer deserves access to fair markets, transparent pricing, and the tools to make informed decisions about their crops.",
"about.missionParagraph2": "KrishiSetu was born from the realization that middlemen were taking up to 40% of farmer profits while buyers struggled with quality and supply chain issues.",
"about.missionParagraph3": "Our platform uses AI to match farmer production with buyer demand, creating a win-win ecosystem where farmers earn more and buyers get better quality produce.",

"about.coreValues": "Our Core Values",
"about.coreValuesDescription": "The principles that guide everything we do at KrishiSetu.",

"about.farmerFirst": "Farmer First",
"about.farmerFirstDescription": "Every decision we make prioritizes farmer welfare and sustainable livelihoods.",

"about.trustTransparency": "Trust & Transparency",
"about.trustTransparencyDescription": "Blockchain-backed contracts ensure fair dealings for all parties.",

"about.innovation": "Innovation",
"about.innovationDescription": "AI-powered tools to predict demand, optimize crops, and maximize profits.",

"about.accessibility": "Accessibility",
"about.accessibilityDescription": "Available in 8 Indian languages, reaching farmers across the nation.",

"about.journey": "Our Journey",
"about.journeyDescription": "Key milestones in our mission to transform Indian agriculture.",

"about.founded": "KrishiSetu Founded",
"about.foundedDescription": "Started with a vision to connect farmers directly with buyers.",

"about.farmersOnboarded": "5,000 Farmers Onboarded",
"about.farmersOnboardedDescription": "Expanded to 5 states with verified farmer networks.",

"about.aiIntegration": "AI Integration",
"about.aiIntegrationDescription": "Launched crop recommendation and demand forecasting tools.",

"about.activeUsers": "10,000+ Active Users",
"about.activeUsersDescription": "Crossed ₹50 crore in total transaction value.",

"about.team": "Meet Our Team",
"about.teamDescription": "Passionate individuals working to revolutionize agriculture in India.",

"about.impact": "Our Impact",
"about.impactDescription": "The numbers that define our success in transforming agricultural practices.",

"about.farmersEmpowered": "Farmers Empowered",
"about.verifiedBuyers": "Verified Buyers",
"about.transactionsFacilitated": "Transactions Facilitated",
"about.reducedCropWastage": "Reduced Crop Wastage",

"about.ctaTitle": "Join the Agricultural Revolution",
"about.ctaDescription": "Whether you're a farmer looking for better markets or a buyer seeking quality produce, KrishiSetu is your partner in growth.",

"about.joinFarmer": "Join as Farmer",
"about.joinBuyer": "Join as Buyer",

"buyerOrders.backToDashboard": "Back to Dashboard",
"buyerOrders.title": "Active Orders",
"buyerOrders.subtitle": "Real-time tracking of orders in logistics transit.",

"buyerOrders.totalOrdersInTransit": "Total Orders in Transit",
"buyerOrders.qualityChecksPassed": "Quality Checks Passed",
"buyerOrders.dispatchedToday": "Dispatched Today",

"buyerOrders.ordersInLogistics": "Orders in Logistics",
"buyerOrders.loading": "Loading active orders...",
"buyerOrders.noActiveOrders": "No active orders available right now.",
"buyerOrders.unableToLoad": "Unable to load active orders.",

"buyerOrders.inTransit": "In Transit",
"buyerOrders.supplier": "Supplier",
"buyerOrders.pickupLocation": "Pickup Location",
"buyerOrders.estArrival": "Est. Arrival",
"buyerOrders.vehicle": "Vehicle #",

"buyerOrders.harvested": "Harvested",
"buyerOrders.qualityInspected": "Quality Inspected",
"buyerOrders.warehouseArrived": "Warehouse Arrived",

"aiRecommendation.back": "Back",
"aiRecommendation.title": "AI Farmer Recommendations",
"aiRecommendation.description": "AI analysed farmers based on crop demand, location and trust score",

"aiRecommendation.land": "Land",
"aiRecommendation.water": "Water",
"aiRecommendation.yield": "Yield",
"aiRecommendation.trustScore": "Trust Score",

"aiRecommendation.available": "Available",
"aiRecommendation.medium": "Medium",
"aiRecommendation.match": "Match",

"aiRecommendation.viewProfile": "View Farmer Profile",
"aiRecommendation.selectFarmer": "Select Farmer",

"analytics.backToDashboard": "Back to Dashboard",
"analytics.title": "Buyer AI Analytics Dashboard",
"analytics.subtitle":
  "AI-powered procurement insights and predictive marketplace recommendations.",
"analytics.procurementSavings": "Procurement Savings Index",
"analytics.lastQuarter": "+12.5% vs last quarter",
"analytics.sourcingWindow": "Optimal Sourcing Window",
"analytics.bestWindow": "Best window: Rice & Onions",
"analytics.supplyVolatility": "Supply Volatility Alert",
"analytics.high": "High",
"analytics.tomatoVolatility": "Tomatoes: +18% volatility",
"analytics.priceForecast": "AI Price Forecast",
"analytics.currentPrice": "Current Price",
"analytics.forecastedPrice": "AI Forecasted Price",
"analytics.logisticsOpportunity": "Logistics & Sourcing Opportunity",
"analytics.qualityAdvisor": "Quality & Grade Advisor",
"analytics.analyticsResults": "AI Analytics Results",
"analytics.endpointData": "Loaded from the buyer analytics endpoint.",
"analytics.loading": "Loading AI analytics...",
"analytics.noData": "No AI analytics data is available at the moment.",

"connectedFarmers.backToDashboard": "Back to Dashboard",
"connectedFarmers.title": "Connected Farmers",
"connectedFarmers.subtitle":
  "Manage farmers connected through KrishiSetu contracts.",
"connectedFarmers.verified": "Verified",
"connectedFarmers.trustScore": "Trust Score",
"connectedFarmers.contract": "Contract",
"connectedFarmers.message": "Message",
"connectedFarmers.loading": "Loading connected farmers...",
"connectedFarmers.error": "Unable to load connected farmers.",
"connectedFarmers.noFarmers": "No connected farmers found yet.",
"connectedFarmers.farmer": "Farmer",
"connectedFarmers.unknown": "Unknown",
"connectedFarmers.unknownLocation": "Unknown Location",

"contractDetails.loading": "Loading contract details...",
"contractDetails.loadError": "Unable to load contract details.",
"contractDetails.notFound": "Contract not found.",
"contractDetails.farmer": "Farmer",
"contractDetails.buyer": "Buyer",
"contractDetails.unknownLocation": "Unknown Location",
"contractDetails.unknownCrop": "Unknown Crop",
"contractDetails.unknown": "Unknown",
"contractDetails.active": "Active",
"contractDetails.backToContracts": "Back to Contracts",
"contractDetails.title": "Contract Details",
"contractDetails.contractId": "Contract ID",
"contractDetails.buyerDetails": "Buyer Details",
"contractDetails.buyerName": "Buyer Name",
"contractDetails.phone": "Phone",
"contractDetails.farmerDetails": "Farmer Details",
"contractDetails.farmerName": "Farmer Name",
"contractDetails.location": "Location",
"contractDetails.cropDetails": "Crop Details",
"contractDetails.cropType": "Crop Type",
"contractDetails.quantity": "Quantity",
"contractDetails.price": "Price",
"contractDetails.transportationDetails": "Transportation Details",
"contractDetails.transportQuestion": "Who will arrange transportation?",
"contractDetails.transportResponsibility": "Transportation Responsibility",
"contractDetails.farmerWillArrange": "Farmer will arrange transportation",
"contractDetails.buyerWillArrange": "Buyer will arrange transportation",
"contractDetails.pickupLocation": "Pickup Location",
"contractDetails.deliveryLocation": "Delivery Location",
"contractDetails.buyerLocation": "Buyer Location",
"contractDetails.deliveryStatus": "Delivery Status",
"contractDetails.pending": "Pending",
"contractDetails.paymentDetails": "Payment Details",
"contractDetails.contractValue": "Contract Value",
"contractDetails.paymentStatus": "Payment Status",
"contractDetails.secured": "Secured",
"contractDetails.settlement": "Settlement",
"contractDetails.afterDelivery": "After Delivery",
"contractDetails.contractTimeline": "Contract Timeline",
"contractDetails.contractCreated": "Contract Created",
"contractDetails.farmerAccepted": "Farmer Accepted",
"contractDetails.cropGrowing": "Crop Growing",
"contractDetails.transportationArranged": "Transportation Arranged",
"contractDetails.cropDelivered": "Crop Delivered",
"contractDetails.finalPayment": "Final Payment",

"contracts.backToDashboard": "Back to Dashboard",
"contracts.title": "Procurement Contracts",
"contracts.searchPlaceholder": "Search by farmer name, contract ID, or crop type...",
"contracts.allStatus": "All Status",
"contracts.active": "Active",
"contracts.pendingFarmerSignature": "Pending Farmer Signature",
"contracts.completed": "Completed",
"contracts.cancelled": "Cancelled",
"contracts.loadError": "Unable to load contracts.",
"contracts.loading": "Loading contracts...",
"contracts.farmer": "Farmer",
"contracts.awaitingFarmerSign": "Awaiting Farmer Sign",
"contracts.activeAndGrowing": "Active & Growing",
"contracts.delivered": "Delivered",
"contracts.pending": "Pending",
"contracts.unknownLocation": "Unknown Location",
"contracts.crop": "Crop",
"contracts.farmerPartner": "Farmer Partner",
"contracts.cropTypeAndVolume": "Crop Type & Volume",
"contracts.locked": "Locked",
"contracts.pricePerKg": "Price per kg",
"contracts.totalSettlementValue": "Total Settlement Value",
"contracts.status": "Status",
"contracts.manageContract": "Manage Contract",
"contracts.noMatch": "No contracts match your filters.",
"contracts.adjustSearch": "Try adjusting your search criteria or status filter.",
"contracts.showing": "Showing",
"contracts.of": "of",
"contracts.contracts": "contracts",

"buyerDashboard.dashboard": "Dashboard",
"buyerDashboard.postRequirement": "Post Requirement",
"buyerDashboard.myRequirements": "My Requirements",
"buyerDashboard.myContracts": "My Contracts",
"buyerDashboard.activeOrders": "Active Orders",
"buyerDashboard.connectedFarmers": "Connected Farmers",
"buyerDashboard.analytics": "Analytics",
"buyerDashboard.messages": "Messages",
"buyerDashboard.profile": "Profile",
"buyerDashboard.logout": "Logout",
"buyerDashboard.postedRequirements": "Posted Requirements",
"buyerDashboard.postedRequirementsSubtitle": "Your current procurement posts",
"buyerDashboard.pendingFarmerRequests": "Pending Farmer Requests",
"buyerDashboard.pendingFarmerRequestsSubtitle": "Awaiting farmer responses",
"buyerDashboard.activeContracts": "Active Contracts",
"buyerDashboard.activeContractsSubtitle": "Contracts in progress",
"buyerDashboard.completedContracts": "Completed Contracts",
"buyerDashboard.completedContractsSubtitle": "Successfully fulfilled deals",
"buyerDashboard.totalSpending": "Total Spending",
"buyerDashboard.totalSpendingSubtitle": "Settled procurement value",
"buyerDashboard.loading": "Loading...",
"buyerDashboard.error": "Unable to load dashboard data.",
"buyerDashboard.title": "Buyer Dashboard",
"buyerDashboard.welcome": "Welcome Back, FreshMart 👋",
"buyerDashboard.description": "Simplify your agricultural procurement. Use our AI tools to match and bridge contracts directly with verified farmers.",
"buyerDashboard.aiFarmerMatching": "AI Farmer Matching",
"buyerDashboard.smartEngine": "Smart Engine",
"buyerDashboard.matchingDescription": "Our smart matchmaking algorithm instantly pairs your crop requirement metrics with verified growers.",
"buyerDashboard.findMatches": "Find Matches Now",
"buyerDashboard.instantMetricsMatch": "Instant Metrics Match",
"buyerDashboard.instantMetricsDescription": "Filters farmers based on active harvest periods, location proximity, and requested crop varieties automatically.",
"buyerDashboard.trustScoreEvaluation": "Trust Score Evaluation",
"buyerDashboard.trustScoreDescription": "Ranks growers through verified history, pricing reliability, and past fulfillment rates to lower procurement risks.",
"buyerDashboard.optimizedNegotiations": "Optimized Negotiations",
"buyerDashboard.optimizedNegotiationsDescription": "Provides intelligent starting price brackets derived from real-time local mandi rates and volume parameters.",
"buyerDashboard.logoutConfirmation": "Are you sure you want to logout?",
"buyerDashboard.logoutDescription": "You will need to enter your credentials again to access your dashboard panels.",
"buyerDashboard.cancel": "Cancel",
"buyerDashboard.yesLogout": "Yes, Logout",

"farmerProfile.back": "Back",
"farmerProfile.notFound": "Farmer not found",
"farmerProfile.verifiedFarmer": "Verified Farmer",
"farmerProfile.land": "Land",
"farmerProfile.water": "Water",
"farmerProfile.expectedYield": "Expected Yield",
"farmerProfile.trustScore": "Trust Score",
"farmerProfile.sendRequirementRequest": "Send Requirement Request",

"buyerLogin.backToHome": "Back to Home",
"buyerLogin.joinAsBuyer": "Join KrishiSetu as Buyer",
"buyerLogin.welcomeBack": "Welcome Back, Buyer",
"buyerLogin.registerDescription": "Create your account to start sourcing directly from farmers",
"buyerLogin.loginDescription": "Sign in to access your marketplace and orders",
"buyerLogin.login": "Login",
"buyerLogin.register": "Register",
"buyerLogin.fullName": "Full Name",
"buyerLogin.enterFullName": "Enter your full name",
"buyerLogin.phoneNumber": "Phone Number",
"buyerLogin.enterPhone": "Enter 10 digit number",
"buyerLogin.password": "Password",
"buyerLogin.companyName": "Company Name (Optional)",
"buyerLogin.businessName": "Business name",
"buyerLogin.completeRegistration": "Complete Registration",
"buyerLogin.signIn": "Sign In",
"buyerLogin.secureTrade": "Secure Trade",
"buyerLogin.verifiedUsers": "Verified Users",
"buyerLogin.registrationSuccess": "Buyer Registration Successful!",
"buyerLogin.registrationFailed": "Registration failed.",
"buyerLogin.loginSuccess": "Login Successful!",
"buyerLogin.loginFailed": "Login failed.",
"buyerLogin.somethingWentWrong": "Something went wrong!",

"buyerMessages.backToDashboard": "Back to Dashboard",
"buyerMessages.growerNetworks": "Grower Networks",
"buyerMessages.searchFarmers": "Search farmers...",
"buyerMessages.trustScore": "Trust Score",
"buyerMessages.typeMessage": "Type your message...",
"buyerMessages.typeYourMessage": "Type your message...",
"buyerMessages.verified": "Verified",

"myRequirements.backToDashboard": "Back to Dashboard",
"myRequirements.title": "My Posted Requirements",
"myRequirements.subtitle": "View all your active crop requirements and procurement demands.",
"myRequirements.loading": "Loading your requirements...",
"myRequirements.loadErrorTitle": "Unable to Load Requirements",
"myRequirements.noRequirementsTitle": "No Requirements Posted Yet",
"myRequirements.noRequirementsDescription": "There are currently no requirements found for your account.",
"myRequirements.active": "Active",
"myRequirements.quantity": "Quantity",
"myRequirements.targetPrice": "Target Price",
"myRequirements.deadline": "Deadline",
"myRequirements.na": "N/A",
"myRequirements.unableToLoad": "Unable to load your requirements. Please try again.",

"notifications.title": "Notifications",
"notifications.subtitle": "Stay updated with your KrishiSetu activities.",
"notifications.markAllAsRead": "Mark all as read",
"notifications.loading": "Loading notifications...",
"notifications.error": "Unable to load notifications.",
"notifications.new": "New",
"notifications.viewDetails": "View Details →",
"notifications.noNotifications": "No notifications yet.",

buyerAIInsightsTitle: "AI Market Insights",
buyerAIInsightsSubtitle:
  "Personalized recommendations powered by KrishiSetu AI",
highDemandAlert: "High Demand Alert",
wheatDemandIncrease:
  "Wheat demand is expected to increase by 18% in the next 30 days.",
pricePrediction: "Price Prediction",
tomatoPriceIncrease:
  "Tomato prices may increase due to lower expected production.",
bestProcurementTime: "Best Procurement Time",
bookContracts:
  "Book contracts within the next 7 days for better pricing.",

  buyerInformation: "Buyer Information",
fullName: "Full Name",
email: "Email",
phoneNumber: "Phone Number",
location: "Location",
companyDetails: "Company Details",
optional: "Optional",
companyName: "Company Name",
businessType: "Business Type",
gstNumber: "GST Number",
companyAddress: "Company Address",
notAvailable: "Not Available",
noCompanyAdded: "No Company Added",
individualBuyerMessage:
  "This buyer is registered as an individual buyer.",

  buyer: "Buyer",
changePhoto: "Change Photo",
verifiedBuyer: "Verified Buyer",
gst: "GST",
address: "Address",
editProfile: "Edit Profile",
memberSince: "Member Since",
buyerType: "Buyer Type",
completedOrders: "Completed Orders",
trustScore: "Trust Score",
outOf100: "out of 100",
trustedByVerifiedFarmers:
  "Trusted by verified farmers on KrishiSetu",
platinumTrustedBuyer: "💎 Platinum Trusted Buyer",
goldTrustedBuyer: "🏅 Gold Trusted Buyer",
silverTrustedBuyer: "🥈 Silver Trusted Buyer",
bronzeTrustedBuyer: "🥉 Bronze Trusted Buyer",

purchaseHistory: "Purchase History",
recentProcurementRecords: "Recent procurement records",
farmer: "Farmer",
quantity: "Quantity",
delivered: "Delivered",
completed: "Completed",

currentBuyingRequirements: "Current Buying Requirements",
activeRecords: "Active Records",
loadingRequirements: "Loading requirements...",
couldNotLoadRequirements: "Could not load requirements.",
noRequirementsFound: "No requirements found.",
unknownCrop: "Unknown Crop",
unknownLocation: "Unknown location",
priceNotSet: "Price not set",
noDeadlineSet: "No deadline set",
active: "Active",
cancelled: "Cancelled",

farmerReviews: "Farmer Reviews",
paymentReleasedOnTime: "Payment was released on time. Very professional buyer.",
communicationWasSmooth: "Communication was smooth and contract process was transparent.",
highlyRecommended: "Highly recommended. Quality verification was fair and quick.",

connectedFarmers: "Connected Farmers",
activeRequirements: "Active Requirements",
averageRating: "Average Rating",

backToDashboard: "Back to Dashboard",
loadingProfile: "Loading profile...",
loadProfile: "Unable to load profile",
updateProfile: "Unable to update profile",

"farmerRequest.back": "Back",
"farmerRequest.farmerNotFound": "Farmer not found",
"farmerRequest.title": "Farmer Request",
"farmerRequest.subtitle": "Send collaboration request to farmer",
"farmerRequest.selectedFarmer": "Selected Farmer",
"farmerRequest.trustScore": "Trust Score",
"farmerRequest.contractFarmingRequest": "Contract Farming Request",
"farmerRequest.requestDescription":
  "Your crop requirement request will be sent to this farmer. Farmer can accept or reject the request.",
"farmerRequest.sendRequest": "Send Request",
"farmerRequest.requestSentSuccessfully":
  "Request sent successfully to farmer!",

"buyerSettings.backToDashboard": "Back to Dashboard",
"buyerSettings.title": "Buyer Account Settings",
"buyerSettings.subtitle": "Manage corporate credentials, GST details, security, and invoice preferences.",

"buyerSettings.tabs.accountPassword": "Account & Password",
"buyerSettings.tabs.taxBusinessKyc": "Tax & Business KYC",
"buyerSettings.tabs.procurementAlerts": "Procurement Alerts",
"buyerSettings.tabs.dangerZone": "Account Danger Zone",

"buyerSettings.security.title": "Security & Login Details",
"buyerSettings.security.description": "Manage password and primary contact email.",
"buyerSettings.security.officialWorkEmail": "Official Work Email",
"buyerSettings.security.currentPassword": "Current Password",
"buyerSettings.security.newPassword": "New Password",
"buyerSettings.security.newPasswordPlaceholder": "Enter new strong password",
"buyerSettings.security.saveChanges": "Save Security Changes",

"buyerSettings.business.title": "Business Verification & GST",
"buyerSettings.business.description": "Update company tax identification for automated invoicing.",
"buyerSettings.business.gstinNumber": "GSTIN Number",
"buyerSettings.business.tradeLicense": "Company Trade License No.",
"buyerSettings.business.updateTaxInfo": "Update Tax Info",

"buyerSettings.notifications.title": "Procurement Alerts",
"buyerSettings.notifications.description": "Configure email and order notifications for sourcing.",
"buyerSettings.notifications.farmerMatchTitle": "New Farmer Match Alerts 🌱",
"buyerSettings.notifications.farmerMatchDescription": "Get notified when farmers post crop listings matching your active procurement requirements.",
"buyerSettings.notifications.contractTitle": "Contract Acceptance & PDF Confirmations 📑",
"buyerSettings.notifications.contractDescription": "Receive instant contract copies as soon as a farmer signs or accepts your offer.",
"buyerSettings.notifications.weeklyDigestTitle": "Weekly Market Sourcing Digest",
"buyerSettings.notifications.weeklyDigestDescription": "Get a summary email of newly listed crop yields in your targeted regions.",

"buyerSettings.danger.title": "Account Danger Zone",
"buyerSettings.danger.description": "Manage corporate account status.",
"buyerSettings.danger.deactivateTitle": "Deactivate Corporate Buyer Account",
"buyerSettings.danger.deactivateDescription": "Deactivating will pause all active procurement requests and remove your listings from the farmer matching feed.",
"buyerSettings.danger.deactivateAccount": "Deactivate Account",

"buyerLayout.goToHomepage": "Go to Homepage",
"buyerLayout.searchPlaceholder": "Search farmers, crops, contracts...",
"buyerLayout.postRequirement": "Post Requirement",
"buyerLayout.post": "Post",
"buyerLayout.notifications": "Notifications",
"buyerLayout.buyerProfile": "Buyer Profile",
"buyerLayout.verifiedBuyer": "Verified Buyer",
"buyerLayout.myProfile": "My Profile",
"buyerLayout.accountSettings": "Account Settings",

},


  hi: {
    "navbar.home": "होम",
    "navbar.about": "हमारे बारे में",
    "navbar.features": "विशेषताएं",
    "navbar.login": "लॉगिन",
    "navbar.dashboard": "डैशबोर्ड",
"navbar.faq": "सामान्य प्रश्न",
"navbar.contact": "संपर्क",
"navbar.farmerLogin": "किसान लॉगिन",
"navbar.buyerLogin": "खरीदार लॉगिन",
"navbar.registerFarmer": "किसान के रूप में पंजीकरण करें",
"navbar.registerBuyer": "खरीदार के रूप में पंजीकरण करें",
"hero.badge": "AI-संचालित मांग-आधारित खेती",
"hero.titleStart": "बिना यह जाने क्यों उगाएं कि",
"hero.titleHighlight": "कौन खरीदेगा?",
"hero.description": "एक AI-संचालित मांग-आधारित कृषि प्लेटफ़ॉर्म जो पारदर्शी समझौतों, भरोसेमंद लेनदेन और मांग-आधारित खेती के माध्यम से किसानों को सीधे खरीदारों से जोड़ता है।",
"hero.farmerButton": "किसान लॉगिन / पंजीकरण",
"hero.buyerButton": "खरीदार लॉगिन / पंजीकरण",
"hero.farmers": "किसान",
"hero.buyers": "खरीदार",
"hero.agreements": "समझौते",
"hero.demandForecast": "मांग का पूर्वानुमान",
"hero.verifiedBuyer": "सत्यापित खरीदार",
"hero.contractReady": "अनुबंध तैयार",
"why.eyebrow": "कृषि सेतु क्यों?",
"why.title": "विश्वास और बुद्धिमत्ता के साथ खेती का नया रूप",
"why.description": "आत्मविश्वास के साथ उगाने और निश्चितता के साथ बेचने के लिए आवश्यक सब कुछ।",

"why.demand.title": "मांग-आधारित खेती",
"why.demand.description": "किसान अनिश्चितता के बजाय वास्तविक बाजार की मांग के आधार पर फसल उगाते हैं।",

"why.connection.title": "सीधा किसान-खरीदार संपर्क",
"why.connection.description": "बिचौलियों पर निर्भरता कम करें और अपनी उपज का अधिक मूल्य प्राप्त करें।",

"why.agreements.title": "स्मार्ट डिजिटल समझौते",
"why.agreements.description": "किसानों और खरीदारों के बीच पारदर्शी अनुबंध।",

"why.trust.title": "विश्वास और प्रतिष्ठा प्रणाली",
"why.trust.description": "प्रतिष्ठा बैज द्वारा समर्थित विश्वसनीय लेनदेन।",
"how.eyebrow": "यह कैसे काम करता है",
"how.title": "आवश्यकता से डिलीवरी तक पांच चरणों में",
"how.description": "किसानों और खरीदारों दोनों के लिए एक स्पष्ट और पारदर्शी प्रक्रिया।",

"how.step1": "खरीदार आवश्यकता पोस्ट करता है",
"how.step2": "किसान अनुबंध स्वीकार करता है",
"how.step3": "समझौता तैयार होता है",
"how.step4": "खेती और निगरानी",
"how.step5": "डिलीवरी और भुगतान",
"impact.eyebrow": "हमारा प्रभाव",
"impact.title": "वास्तविक बदलाव, विश्वास और आय में मापा गया",

"impact.waste": "फसल की बर्बादी में कमी",
"impact.income": "किसानों की आय में वृद्धि",
"impact.market": "बेहतर बाजार पहुंच",
"impact.transactions": "पारदर्शी लेनदेन",
"trust.eyebrow": "विश्वास और प्रतिष्ठा",
"trust.title": "विश्वास अर्जित करें, अवसर प्राप्त करें",
"trust.description": "सफल समझौतों, समय पर डिलीवरी, गुणवत्ता अनुपालन और सकारात्मक लेनदेन इतिहास के माध्यम से बैज अर्जित किए जाते हैं।",

"trust.bronze": "कांस्य बैज",
"trust.silver": "रजत बैज",
"trust.gold": "स्वर्ण बैज",
"trust.platinum": "प्लेटिनम बैज",

"trust.verifiedUser": "सत्यापित उपयोगकर्ता",
"trust.reliablePartner": "विश्वसनीय साझेदार",
"trust.highlyTrusted": "अत्यधिक विश्वसनीय",
"trust.eliteMember": "विशिष्ट सदस्य",
"testimonials.eyebrow": "ग्राहक अनुभव",
"testimonials.title": "किसानों और खरीदारों दोनों का भरोसा",

"testimonials.ramesh.role": "किसान, महाराष्ट्र",
"testimonials.ramesh.quote": "अब मैं वही उगाता हूं जिसकी खरीदारों को वास्तव में जरूरत होती है। मेरी आय अधिक स्थिर है और मेरी फसल की बर्बादी भी काफी कम हो गई है।",

"testimonials.lakshmi.role": "किसान, तेलंगाना",
"testimonials.lakshmi.quote": "डिजिटल समझौतों ने मुझे विश्वास दिया। भुगतान समय पर मिलता है और बिचौलियों को कोई हिस्सा नहीं देना पड़ता।",

"testimonials.anand.role": "खरीदार, दिल्ली",
"testimonials.anand.quote": "आवश्यकता पोस्ट करने और सत्यापित किसानों से जुड़ने से हमारी खरीद प्रक्रिया विश्वसनीय और पारदर्शी हो गई है।",

"testimonials.meera.role": "थोक खरीदार, गुजरात",
"testimonials.meera.quote": "प्रतिष्ठा बैज हमें जल्दी से विश्वसनीय साझेदार चुनने में मदद करते हैं। गुणवत्ता और डिलीवरी लगातार अच्छी रही है।",

"financial.eyebrow": "वित्तीय सहायता",
"financial.title": "आपके साथ बढ़ने वाली वित्तीय सहायता और सुरक्षा",
"financial.description": "उन वित्तीय साधनों तक पहुंच प्राप्त करें जो खेती को टिकाऊ और सुरक्षित बनाते हैं।",

"financial.banks.title": "बैंक और ऋण सुविधा",
"financial.banks.description": "समय पर कृषि ऋण के लिए ऋणदाताओं से जुड़ें।",

"financial.insurance.title": "फसल बीमा",
"financial.insurance.description": "मौसम और बाजार के जोखिमों से अपनी फसल की सुरक्षा करें।",

"financial.schemes.title": "सरकारी योजनाएं",
"financial.schemes.description": "प्रासंगिक सब्सिडी और सरकारी योजनाओं को खोजें और उनके लिए आवेदन करें।",

"financial.literacy.title": "वित्तीय साक्षरता",
"financial.literacy.description": "खेती के चक्रों के अनुसार स्मार्ट धन प्रबंधन सीखें।",

"fpo.eyebrow": "एफपीओ और समुदाय",
"fpo.title": "किसान समुदायों के माध्यम से जुड़ें",
"fpo.description": "एक साथ मजबूत — सहयोग करें, बातचीत करें और एक साथ आगे बढ़ें।",

"fpo.organizations.title": "किसान उत्पादक संगठन",
"fpo.organizations.description": "सत्यापित एफपीओ से जुड़ें और एक समूह के रूप में साथ मिलकर आगे बढ़ें।",

"fpo.selling.title": "सामूहिक बिक्री",
"fpo.selling.description": "बड़े खरीदारों और बेहतर कीमतों तक पहुंचने के लिए अपनी उपज को एक साथ बेचें।",

"fpo.negotiation.title": "बेहतर बातचीत की शक्ति",
"fpo.negotiation.description": "अधिक मात्रा और विश्वास के साथ बेहतर शर्तों पर बातचीत करें।",

"fpo.community.title": "सामुदायिक सहयोग",
"fpo.community.description": "पूरे नेटवर्क में ज्ञान, संसाधन और सहयोग साझा करें।",

"cta.title": "कृषि के भविष्य से जुड़ें",
"cta.description": "चाहे आप किसान हों या खरीदार, KrishiSetu आपको विश्वसनीय और लाभदायक साझेदारी बनाने में मदद करता है।",
"cta.farmer": "किसान के रूप में जुड़ें",
"cta.buyer": "खरीदार के रूप में जुड़ें",

"footer.description": "एक AI-संचालित मांग-आधारित कृषि प्लेटफॉर्म जो पारदर्शी और विश्वास-आधारित समझौतों के माध्यम से किसानों को सीधे खरीदारों से जोड़ता है।",

"footer.company": "कंपनी",
"footer.portals": "पोर्टल",
"footer.followUs": "हमसे जुड़ें",

"footer.about": "हमारे बारे में",
"footer.features": "विशेषताएं",
"footer.contact": "संपर्क करें",
"footer.faq": "सामान्य प्रश्न",

"footer.farmerLogin": "किसान लॉगिन",
"footer.farmerRegister": "किसान पंजीकरण",
"footer.buyerLogin": "खरीदार लॉगिन",
"footer.buyerRegister": "खरीदार पंजीकरण",

"footer.facebook": "फेसबुक",
"footer.twitter": "ट्विटर",
"footer.whatsapp": "व्हाट्सऐप",
"footer.telegram": "टेलीग्राम",

"footer.rights": "सर्वाधिकार सुरक्षित।",

"languages.eyebrow": "बहुभाषी समर्थन",
"languages.title": "खेती कई भाषाएं बोलती है",
"languages.description": "KrishiSetu का उपयोग अपनी पसंदीदा भाषा में आसानी से करें।",

"ai.eyebrow": "AI तकनीक",
"ai.title": "AI-संचालित कृषि बुद्धिमत्ता",
"ai.description": "डेटा की मदद से बीज से बिक्री तक बेहतर और स्मार्ट निर्णय लें।",

"ai.cropRecommendation": "फसल की सिफारिश",
"ai.cropRecommendationDesc": "AI मिट्टी, मौसम और मांग के आधार पर सबसे लाभदायक फसलों का सुझाव देता है।",

"ai.demandForecasting": "मांग का पूर्वानुमान",
"ai.demandForecastingDesc": "आने वाली बाजार मांग का अनुमान लगाएं और वही उगाएं जिसकी बिक्री हो।",

"ai.marketTrend": "बाजार रुझान विश्लेषण",
"ai.marketTrendDesc": "विभिन्न क्षेत्रों में कीमतों और बाजार के रुझानों को रियल टाइम में ट्रैक करें।",

"ai.profitEstimation": "लाभ का अनुमान",
"ai.profitEstimationDesc": "डेटा-आधारित अनुमान के साथ बुवाई से पहले अपने संभावित लाभ का अनुमान लगाएं।",
"buyerCta.forBuyers": "खरीदारों के लिए",
"buyerCta.title": "क्या आप किसी विशेष फसल की तलाश में हैं?",
"buyerCta.description": "क्या आपको फूल, फल, सब्जियां, अनाज या बड़ी मात्रा में कृषि उत्पाद चाहिए? अपनी आवश्यकता पोस्ट करने और सीधे आपूर्ति प्राप्त करने के लिए लॉगिन करें।",
"buyerCta.login": "आवश्यकता पोस्ट करने के लिए लॉगिन करें",
"buyerCta.footer": "KrishiSetu पर मांग बनाने वाले पहले खरीदार बनें।",

"marketplace.title": "खरीदार आवश्यकताएँ मार्केटप्लेस",
"marketplace.subtitle": "सत्यापित खरीदारों की थोक फसल खरीद आवश्यकताओं को देखें और प्रतिक्रिया दें",
"marketplace.searchPlaceholder": "फसल का नाम या कंपनी खोजें...",
"marketplace.all": "सभी",
"marketplace.vegetables": "सब्ज़ियाँ",
"marketplace.grains": "अनाज",
"marketplace.fruits": "फल",
"marketplace.pulses": "दालें",
"marketplace.filters": "फ़िल्टर",
"marketplace.advancedFilters": "उन्नत फ़िल्टर",
"marketplace.minimumPrice": "न्यूनतम कीमत (₹)",
"marketplace.pricePlaceholder": "जैसे, 1500",
"marketplace.locationRadius": "स्थान की दूरी (किमी)",
"marketplace.radiusPlaceholder": "जैसे, 50",
"marketplace.resetFilters": "फ़िल्टर रीसेट करें",
"marketplace.fetchingRequirements": "लाइव आवश्यकताएँ प्राप्त की जा रही हैं...",
"marketplace.showing": "दिखाया जा रहा है",
"marketplace.requirement": "आवश्यकता",
"marketplace.requirements": "आवश्यकताएँ",
"marketplace.verifiedBuyer": "सत्यापित खरीदार",
"marketplace.requiredCrop": "आवश्यक फसल",
"marketplace.qualityGrade": "गुणवत्ता ग्रेड",
"marketplace.expectedPrice": "अपेक्षित कीमत",
"marketplace.deliveryLocation": "डिलीवरी स्थान",
"marketplace.requiredBy": "आवश्यकता की अंतिम तिथि",
"marketplace.sendSupplyProposal": "आपूर्ति प्रस्ताव भेजें",
"marketplace.noRequirements": "कोई आवश्यकता नहीं मिली",
"marketplace.adjustSearch": "अधिक अवसर खोजने के लिए अपनी खोज या फ़िल्टर बदलकर देखें",
"marketplace.proposalSent": "प्रस्ताव भेजा गया",
"marketplace.contactedShortly": "आपसे जल्द ही संपर्क किया जाएगा।",
"marketplace.failedToLoad": "आवश्यकताएँ लोड करने में विफल।",

"chat.myChats": "मेरी चैट्स",
"chat.searchContacts": "कॉन्टैक्ट खोजें...",
"chat.activeNow": "अभी सक्रिय",
"chat.typeMessage": "अपना संदेश यहाँ लिखें...",
"chat.attachFile": "फ़ाइल अटैच करें",
"chat.sendMessage": "संदेश भेजें",
"chat.selectConversation": "चैट शुरू करने के लिए बातचीत चुनें",

"cropCard.acres": "एकड़",
"cropCard.growthStage": "विकास चरण",
"cropCard.estimatedHarvest": "अनुमानित फसल कटाई",
"cropCard.healthy": "स्वस्थ",
"cropCard.excellent": "उत्कृष्ट",
"cropCard.needsAttention": "ध्यान देने की आवश्यकता",

"cropRequirement.backToDashboard": "डैशबोर्ड पर वापस जाएँ",
"cropRequirement.title": "नई फसल आवश्यकता पोस्ट करें",
"cropRequirement.subtitle": "अपनी फसल की आवश्यकताएँ बताएं और सत्यापित किसानों से सीधे प्रतिस्पर्धी आपूर्ति प्रस्ताव प्राप्त करें।",
"cropRequirement.cropName": "फसल का नाम",
"cropRequirement.cropNamePlaceholder": "फसल का नाम दर्ज करें (जैसे गेहूँ, टमाटर)...",
"cropRequirement.qualityGrade": "आवश्यक गुणवत्ता/ग्रेड",
"cropRequirement.selectGrade": "ग्रेड चुनें (वैकल्पिक)...",
"cropRequirement.gradeA": "ग्रेड A (प्रीमियम)",
"cropRequirement.gradeB": "ग्रेड B (मानक)",
"cropRequirement.organicCertified": "जैविक प्रमाणित",
"cropRequirement.quantityNeeded": "आवश्यक मात्रा",
"cropRequirement.enterQuantity": "मात्रा दर्ज करें",
"cropRequirement.targetPrice": "लक्षित मूल्य (कुल / अपेक्षित)",
"cropRequirement.deliveryDeadline": "डिलीवरी की अंतिम तिथि",
"cropRequirement.deliveryLocation": "डिलीवरी स्थान",
"cropRequirement.locationPlaceholder": "जैसे, इंदौर, दिल्ली मंडी",
"cropRequirement.additionalTerms": "अतिरिक्त अनुबंध शर्तें",
"cropRequirement.optional": "वैकल्पिक",
"cropRequirement.termsPlaceholder": "जैसे, नमी अधिकतम 12%, प्रीमियम पैकेजिंग आवश्यक...",
"cropRequirement.publish": "खरीद मांग प्रकाशित करें →",
"cropRequirement.publishing": "प्रकाशित हो रहा है...",
"cropRequirement.publishedSuccess": "आपकी खरीद आवश्यकता सफलतापूर्वक प्रकाशित हो गई है! रीडायरेक्ट किया जा रहा है...",
"cropRequirement.verifiedNetwork": "100% सत्यापित किसान नेटवर्क मिलान",
"cropRequirement.mandiPricing": "सरकारी मंडी मूल्य संदर्भ के अनुरूप",
"cropRequirement.predictorAI": "कृषिसेतु प्रेडिक्टर AI",
"cropRequirement.demandScore": "मांग स्कोर",
"cropRequirement.highMarketDemand": "बाजार में उच्च मांग",
"cropRequirement.availableFarmers": "उपलब्ध किसान",
"cropRequirement.estimatedResponses": "अनुमानित प्रतिक्रियाएँ",
"cropRequirement.suggestedPrice": "सुझाया गया मूल्य",
"cropRequirement.priceBelowAverage": "आपका वर्तमान दर्ज मूल्य",
"cropRequirement.belowClusterAverage": "वर्तमान माइक्रो-क्लस्टर औसत से कम है।",
"cropRequirement.typeTomato": "फसल के नाम में",
"cropRequirement.inCropName": "लिखकर लाइव AI खरीद प्रतिक्रिया मिलान का सिमुलेशन करें।",
"cropRequirement.supportModule": "💡 खरीद निर्णय सहायता मॉड्यूल सक्रिय है",
"cropRequirement.noAuthToken": "कोई प्रमाणीकरण टोकन नहीं मिला। आवश्यकता पोस्ट करने से पहले Buyer के रूप में लॉगिन करें।",
"cropRequirement.sessionExpired": "सेशन समाप्त हो गया है। कृपया Buyer के रूप में दोबारा लॉगिन करें।",
"cropRequirement.accessDenied": "पहुंच अस्वीकृत: केवल Buyers ही आवश्यकताएँ पोस्ट कर सकते हैं।",
"cropRequirement.failedToSubmit": "आवश्यकता सबमिट करने में विफल।",
"cropRequirement.cropRequired": "फसल का चयन आवश्यक है",
"cropRequirement.gradeRequired": "गुणवत्ता/ग्रेड का चयन आवश्यक है",
"cropRequirement.validQuantity": "मान्य मात्रा आवश्यक है",
"cropRequirement.validPrice": "मान्य लक्षित मूल्य आवश्यक है",
"cropRequirement.dateRequired": "डिलीवरी की तारीख आवश्यक है",
"cropRequirement.locationRequired": "डिलीवरी स्थान आवश्यक है",

"cropsHeader.title": "मेरी फसल सूची",
"cropsHeader.subtitle": "अपनी जैविक फसलों का प्रबंधन और निगरानी करें",
"cropsHeader.searchPlaceholder": "फसलें खोजें...",
"cropsHeader.addNewCrop": "नई फसल जोड़ें",

"farmerActivity.recentActivity": "हाल की गतिविधि",
"farmerActivity.contractCompleted": "अनुबंध पूरा हुआ",
"farmerActivity.soldWheat": "FreshMart Pvt Ltd को गेहूँ बेचा",
"farmerActivity.today": "आज",
"farmerActivity.paymentReceived": "भुगतान प्राप्त हुआ",
"farmerActivity.paymentCredited": "₹25,000 सफलतापूर्वक जमा हुए",
"farmerActivity.twoDaysAgo": "2 दिन पहले",
"farmerActivity.newCropListed": "नई फसल सूचीबद्ध",
"farmerActivity.tomatoAdded": "टमाटर बिक्री के लिए जोड़े गए",
"farmerActivity.oneWeekAgo": "1 सप्ताह पहले",

"farmerCrops.title": "मेरी उगाई जाने वाली फसलें",
"farmerCrops.addCrop": "फसल जोड़ें",
"farmerCrops.rabiSeason": "रबी मौसम",
"farmerCrops.kharifSeason": "खरीफ मौसम",
"farmerCrops.winterCrop": "सर्दियों की फसल",
"farmerCrops.allSeason": "सभी मौसम",
"farmerCrops.winter": "सर्दी",
"farmerCrops.active": "सक्रिय",
"farmerCrops.available": "उपलब्ध",
"farmerCrops.listed": "सूचीबद्ध",
"farmerCrops.addNewCrop": "नई फसल जोड़ें",
"farmerCrops.cropName": "फसल का नाम",
"farmerCrops.season": "मौसम",
"farmerCrops.landArea": "भूमि क्षेत्र (एकड़)",
"farmerCrops.expectedYield": "अपेक्षित उपज",
"farmerCrops.saveCrop": "फसल सेव करें",
"farmerCrops.cancel": "रद्द करें",

"farmerDocuments.paymentSummary": "भुगतान सारांश",
"farmerDocuments.walletBalance": "वॉलेट बैलेंस",
"farmerDocuments.pendingPayments": "लंबित भुगतान",
"farmerDocuments.totalEarnings": "कुल कमाई",
"farmerDocuments.documents": "दस्तावेज़",
"farmerDocuments.aadhaarCard": "आधार कार्ड",
"farmerDocuments.landRecord": "भूमि रिकॉर्ड",
"farmerDocuments.bankPassbook": "बैंक पासबुक",
"farmerDocuments.verified": "सत्यापित",

"addCropModal.title": "नई फसल जोड़ें",
"addCropModal.cropName": "फसल का नाम",
"addCropModal.selectCrop": "फसल चुनें...",
"addCropModal.other": "अन्य",
"addCropModal.customCropName": "कस्टम फसल का नाम दर्ज करें",
"addCropModal.customCropPlaceholder": "जैसे: सरसों / गन्ना",
"addCropModal.landArea": "भूमि क्षेत्र (एकड़)",
"addCropModal.landAreaPlaceholder": "जैसे: 2.5",
"addCropModal.harvestDate": "अनुमानित कटाई की तारीख",
"addCropModal.cancel": "रद्द करें",
"addCropModal.saving": "सेव हो रहा है...",
"addCropModal.addCrop": "फसल जोड़ें",
"addCropModal.organicTomatoes": "जैविक टमाटर",
"addCropModal.basmatiRice": "बासमती चावल",
"addCropModal.redOnions": "लाल प्याज़",
"addCropModal.greenChillies": "हरी मिर्च",
"addCropModal.wheat": "गेहूँ",
"addCropModal.potatoes": "आलू",

"farmerStats.activeContracts": "सक्रिय अनुबंध",
"farmerStats.currentlyRunning": "वर्तमान में चल रहे हैं",
"farmerStats.completedContracts": "पूर्ण किए गए अनुबंध",
"farmerStats.successfullyDelivered": "सफलतापूर्वक डिलीवर किए गए",
"farmerStats.totalEarnings": "कुल कमाई",
"farmerStats.lifetimeIncome": "अब तक की आय",
"farmerStats.buyerRating": "खरीदार रेटिंग",
"farmerStats.basedOnReviews": "समीक्षाओं के आधार पर",
"farmerStats.connectedBuyers": "जुड़े हुए खरीदार",
"farmerStats.trustedPartners": "विश्वसनीय साझेदार",

"logoutModal.title": "क्या आप वाकई लॉगआउट करना चाहते हैं?",
"logoutModal.description": "अपने KrishiSetu डैशबोर्ड पैनल तक पहुँचने के लिए आपको फिर से अपनी लॉगिन जानकारी दर्ज करनी होगी।",
"logoutModal.cancel": "रद्द करें",
"logoutModal.confirm": "हाँ, लॉगआउट करें",

"aboutHero.eyebrow": "कृषिसेतु के बारे में",
"aboutHero.title": "किसानों को बेहतर अवसरों से जोड़ना",
"aboutHero.description": "एक पारदर्शी और विश्वसनीय कृषि इकोसिस्टम का निर्माण।",

"farmerTabs.overview": "अवलोकन",
"farmerTabs.crops": "फसलें",
"farmerTabs.activity": "गतिविधि",
"farmerTabs.documents": "दस्तावेज़",

"farmerHero.verifiedFarmer": "सत्यापित किसान",
"farmerHero.editProfile": "प्रोफ़ाइल संपादित करें",
"farmerHero.memberSince": "सदस्यता की शुरुआत",
"farmerHero.experience": "अनुभव",
"farmerHero.landOwned": "स्वामित्व वाली भूमि",
"farmerHero.trustScore": "विश्वास स्कोर",
"farmerHero.outOf": "100 में से",
"farmerHero.goldTrustedFarmer": "🏅 गोल्ड विश्वसनीय किसान",
"farmerHero.trustedBy": "KrishiSetu पर सत्यापित खरीदारों द्वारा विश्वसनीय",
"farmerHero.editFarmerProfile": "किसान प्रोफ़ाइल संपादित करें",
"farmerHero.farmerName": "किसान का नाम",
"farmerHero.location": "स्थान",
"farmerHero.waterSource": "जल स्रोत",
"farmerHero.saveChanges": "परिवर्तन सहेजें",
"farmerHero.cancel": "रद्द करें",

"farmerOverview.aboutMe": "मेरे बारे में",
"farmerOverview.description": "मैं सीहोर, मध्य प्रदेश का एक समर्पित किसान हूँ। मैं आधुनिक कृषि तकनीकों का उपयोग करके उच्च गुणवत्ता वाली फसलें उगाता हूँ और खरीदारों के साथ दीर्घकालिक साझेदारी में विश्वास करता हूँ।",
"farmerOverview.mobile": "मोबाइल",
"farmerOverview.email": "ईमेल",
"farmerOverview.address": "पता",
"farmerOverview.landDetails": "भूमि का विवरण",
"farmerOverview.totalLand": "कुल भूमि",
"farmerOverview.soilType": "मिट्टी का प्रकार",
"farmerOverview.waterSource": "जल स्रोत",
"farmerOverview.organicFarming": "जैविक खेती",
"farmerOverview.yes": "हाँ",

"farmerSidebar.dashboard": "डैशबोर्ड",
"farmerSidebar.myCrops": "मेरी फसलें",
"farmerSidebar.myContracts": "मेरे अनुबंध",
"farmerSidebar.buyerRequirements": "खरीदार की आवश्यकताएँ",
"farmerSidebar.incomingRequests": "आने वाले अनुरोध",
"farmerSidebar.aiAnalytics": "AI विश्लेषण",
"farmerSidebar.messages": "संदेश",
"farmerSidebar.profile": "प्रोफ़ाइल",
"farmerSidebar.logout": "लॉगआउट",

"about.story": "हमारी कहानी",
"about.title": "किसानों को सशक्त बनाना, कृषि को बदलना",
"about.description": "KrishiSetu AI-संचालित मांग-आधारित खेती के माध्यम से किसानों और खरीदारों के बीच की दूरी को कम करता है, जिससे उचित मूल्य और टिकाऊ कृषि पद्धतियां सुनिश्चित होती हैं।",

"about.mission": "हमारा मिशन",
"about.missionParagraph1": "हमारा मानना है कि हर किसान को उचित बाजार, पारदर्शी मूल्य निर्धारण और अपनी फसलों के बारे में सही निर्णय लेने के लिए आवश्यक साधनों तक पहुंच मिलनी चाहिए।",
"about.missionParagraph2": "KrishiSetu की शुरुआत इस समझ से हुई कि बिचौलिए किसानों के मुनाफे का 40% तक हिस्सा ले रहे थे, जबकि खरीदार गुणवत्ता और आपूर्ति श्रृंखला से जुड़ी समस्याओं का सामना कर रहे थे।",
"about.missionParagraph3": "हमारा प्लेटफॉर्म AI का उपयोग करके किसानों के उत्पादन को खरीदारों की मांग से जोड़ता है, जिससे किसानों को अधिक कमाई और खरीदारों को बेहतर गुणवत्ता वाली उपज मिलती है।",

"about.coreValues": "हमारे मूल मूल्य",
"about.coreValuesDescription": "वे सिद्धांत जो KrishiSetu में हमारे हर कार्य का मार्गदर्शन करते हैं।",

"about.farmerFirst": "किसान पहले",
"about.farmerFirstDescription": "हमारा हर निर्णय किसानों के कल्याण और टिकाऊ आजीविका को प्राथमिकता देता है।",

"about.trustTransparency": "विश्वास और पारदर्शिता",
"about.trustTransparencyDescription": "ब्लॉकचेन-आधारित अनुबंध सभी पक्षों के लिए उचित लेनदेन सुनिश्चित करते हैं।",

"about.innovation": "नवाचार",
"about.innovationDescription": "मांग का अनुमान लगाने, फसलों को बेहतर बनाने और मुनाफा बढ़ाने के लिए AI-संचालित उपकरण।",

"about.accessibility": "सुलभता",
"about.accessibilityDescription": "8 भारतीय भाषाओं में उपलब्ध, देशभर के किसानों तक पहुंचने के लिए।",

"about.journey": "हमारा सफर",
"about.journeyDescription": "भारतीय कृषि को बदलने के हमारे मिशन की महत्वपूर्ण उपलब्धियां।",

"about.founded": "KrishiSetu की स्थापना",
"about.foundedDescription": "किसानों को सीधे खरीदारों से जोड़ने के उद्देश्य से शुरुआत की गई।",

"about.farmersOnboarded": "5,000 किसान जुड़े",
"about.farmersOnboardedDescription": "सत्यापित किसान नेटवर्क के साथ 5 राज्यों तक विस्तार किया।",

"about.aiIntegration": "AI एकीकरण",
"about.aiIntegrationDescription": "फसल सिफारिश और मांग पूर्वानुमान उपकरण लॉन्च किए गए।",

"about.activeUsers": "10,000+ सक्रिय उपयोगकर्ता",
"about.activeUsersDescription": "कुल ₹50 करोड़ से अधिक के लेनदेन का आंकड़ा पार किया।",

"about.team": "हमारी टीम से मिलिए",
"about.teamDescription": "भारत में कृषि में क्रांति लाने के लिए काम करने वाले जुनूनी लोग।",

"about.impact": "हमारा प्रभाव",
"about.impactDescription": "कृषि पद्धतियों को बदलने में हमारी सफलता को दर्शाने वाले आंकड़े।",

"about.farmersEmpowered": "सशक्त किसान",
"about.verifiedBuyers": "सत्यापित खरीदार",
"about.transactionsFacilitated": "सुविधा प्रदान किए गए लेनदेन",
"about.reducedCropWastage": "फसल की बर्बादी में कमी",

"about.ctaTitle": "कृषि क्रांति से जुड़ें",
"about.ctaDescription": "चाहे आप बेहतर बाजार की तलाश करने वाले किसान हों या गुणवत्तापूर्ण उपज की तलाश करने वाले खरीदार, KrishiSetu आपके विकास का साथी है।",

"about.joinFarmer": "किसान के रूप में जुड़ें",
"about.joinBuyer": "खरीदार के रूप में जुड़ें",

"buyerOrders.backToDashboard": "डैशबोर्ड पर वापस जाएँ",
"buyerOrders.title": "सक्रिय ऑर्डर",
"buyerOrders.subtitle": "लॉजिस्टिक्स में भेजे गए ऑर्डरों की रियल-टाइम ट्रैकिंग।",

"buyerOrders.totalOrdersInTransit": "ट्रांजिट में कुल ऑर्डर",
"buyerOrders.qualityChecksPassed": "गुणवत्ता जांच सफल",
"buyerOrders.dispatchedToday": "आज भेजे गए ऑर्डर",

"buyerOrders.ordersInLogistics": "लॉजिस्टिक्स में ऑर्डर",
"buyerOrders.loading": "सक्रिय ऑर्डर लोड हो रहे हैं...",
"buyerOrders.noActiveOrders": "इस समय कोई सक्रिय ऑर्डर उपलब्ध नहीं है।",
"buyerOrders.unableToLoad": "सक्रिय ऑर्डर लोड करने में असमर्थ।",

"buyerOrders.inTransit": "ट्रांजिट में",
"buyerOrders.supplier": "आपूर्तिकर्ता",
"buyerOrders.pickupLocation": "पिकअप स्थान",
"buyerOrders.estArrival": "अनुमानित आगमन",
"buyerOrders.vehicle": "वाहन नंबर",

"buyerOrders.harvested": "फसल काटी गई",
"buyerOrders.qualityInspected": "गुणवत्ता जांची गई",
"buyerOrders.warehouseArrived": "वेयरहाउस पहुंच गया",

"aiRecommendation.back": "वापस जाएँ",
"aiRecommendation.title": "AI किसान सिफारिशें",
"aiRecommendation.description": "AI ने फसल की मांग, स्थान और विश्वास स्कोर के आधार पर किसानों का विश्लेषण किया है।",

"aiRecommendation.land": "भूमि",
"aiRecommendation.water": "पानी",
"aiRecommendation.yield": "उपज",
"aiRecommendation.trustScore": "विश्वास स्कोर",

"aiRecommendation.available": "उपलब्ध",
"aiRecommendation.medium": "मध्यम",
"aiRecommendation.match": "मिलान",

"aiRecommendation.viewProfile": "किसान की प्रोफ़ाइल देखें",
"aiRecommendation.selectFarmer": "किसान चुनें",

"analytics.backToDashboard": "डैशबोर्ड पर वापस जाएं",
"analytics.title": "खरीदार AI विश्लेषण डैशबोर्ड",
"analytics.subtitle":
  "AI द्वारा संचालित खरीद संबंधी जानकारी और भविष्य के बाजार सुझाव।",
"analytics.procurementSavings": "खरीद बचत सूचकांक",
"analytics.lastQuarter": "पिछली तिमाही की तुलना में +12.5%",
"analytics.sourcingWindow": "सर्वोत्तम खरीद समय",
"analytics.bestWindow": "सर्वोत्तम समय: चावल और प्याज",
"analytics.supplyVolatility": "आपूर्ति अस्थिरता चेतावनी",
"analytics.high": "उच्च",
"analytics.tomatoVolatility": "टमाटर: +18% अस्थिरता",
"analytics.priceForecast": "AI मूल्य पूर्वानुमान",
"analytics.currentPrice": "वर्तमान मूल्य",
"analytics.forecastedPrice": "AI अनुमानित मूल्य",
"analytics.logisticsOpportunity": "लॉजिस्टिक्स और खरीद अवसर",
"analytics.qualityAdvisor": "गुणवत्ता और ग्रेड सलाहकार",
"analytics.analyticsResults": "AI विश्लेषण परिणाम",
"analytics.endpointData": "खरीदार विश्लेषण API से प्राप्त डेटा।",
"analytics.loading": "AI विश्लेषण लोड हो रहा है...",
"analytics.noData": "इस समय कोई AI विश्लेषण डेटा उपलब्ध नहीं है।",

"connectedFarmers.backToDashboard": "डैशबोर्ड पर वापस जाएं",
"connectedFarmers.title": "जुड़े हुए किसान",
"connectedFarmers.subtitle":
  "KrishiSetu अनुबंधों के माध्यम से जुड़े किसानों का प्रबंधन करें।",
"connectedFarmers.verified": "सत्यापित",
"connectedFarmers.trustScore": "विश्वास स्कोर",
"connectedFarmers.contract": "अनुबंध",
"connectedFarmers.message": "संदेश",
"connectedFarmers.loading": "जुड़े हुए किसानों को लोड किया जा रहा है...",
"connectedFarmers.error": "जुड़े हुए किसानों को लोड नहीं किया जा सका।",
"connectedFarmers.noFarmers": "अभी तक कोई जुड़े हुए किसान नहीं मिले।",
"connectedFarmers.farmer": "किसान",
"connectedFarmers.unknown": "अज्ञात",
"connectedFarmers.unknownLocation": "अज्ञात स्थान",

"contractDetails.loading": "कॉन्ट्रैक्ट विवरण लोड हो रहा है...",
"contractDetails.loadError": "कॉन्ट्रैक्ट विवरण लोड करने में असमर्थ।",
"contractDetails.notFound": "कॉन्ट्रैक्ट नहीं मिला।",
"contractDetails.farmer": "किसान",
"contractDetails.buyer": "खरीदार",
"contractDetails.unknownLocation": "अज्ञात स्थान",
"contractDetails.unknownCrop": "अज्ञात फसल",
"contractDetails.unknown": "अज्ञात",
"contractDetails.active": "सक्रिय",
"contractDetails.backToContracts": "कॉन्ट्रैक्ट्स पर वापस जाएँ",
"contractDetails.title": "कॉन्ट्रैक्ट विवरण",
"contractDetails.contractId": "कॉन्ट्रैक्ट आईडी",
"contractDetails.buyerDetails": "खरीदार का विवरण",
"contractDetails.buyerName": "खरीदार का नाम",
"contractDetails.phone": "फ़ोन",
"contractDetails.farmerDetails": "किसान का विवरण",
"contractDetails.farmerName": "किसान का नाम",
"contractDetails.location": "स्थान",
"contractDetails.cropDetails": "फसल का विवरण",
"contractDetails.cropType": "फसल का प्रकार",
"contractDetails.quantity": "मात्रा",
"contractDetails.price": "कीमत",
"contractDetails.transportationDetails": "परिवहन का विवरण",
"contractDetails.transportQuestion": "परिवहन की व्यवस्था कौन करेगा?",
"contractDetails.transportResponsibility": "परिवहन की जिम्मेदारी",
"contractDetails.farmerWillArrange": "किसान परिवहन की व्यवस्था करेगा",
"contractDetails.buyerWillArrange": "खरीदार परिवहन की व्यवस्था करेगा",
"contractDetails.pickupLocation": "पिकअप स्थान",
"contractDetails.deliveryLocation": "डिलीवरी स्थान",
"contractDetails.buyerLocation": "खरीदार का स्थान",
"contractDetails.deliveryStatus": "डिलीवरी स्थिति",
"contractDetails.pending": "लंबित",
"contractDetails.paymentDetails": "भुगतान का विवरण",
"contractDetails.contractValue": "कॉन्ट्रैक्ट मूल्य",
"contractDetails.paymentStatus": "भुगतान स्थिति",
"contractDetails.secured": "सुरक्षित",
"contractDetails.settlement": "निपटान",
"contractDetails.afterDelivery": "डिलीवरी के बाद",
"contractDetails.contractTimeline": "कॉन्ट्रैक्ट टाइमलाइन",
"contractDetails.contractCreated": "कॉन्ट्रैक्ट बनाया गया",
"contractDetails.farmerAccepted": "किसान ने स्वीकार किया",
"contractDetails.cropGrowing": "फसल उगाई जा रही है",
"contractDetails.transportationArranged": "परिवहन की व्यवस्था की गई",
"contractDetails.cropDelivered": "फसल डिलीवर की गई",
"contractDetails.finalPayment": "अंतिम भुगतान",

"contracts.backToDashboard": "डैशबोर्ड पर वापस जाएँ",
"contracts.title": "खरीद कॉन्ट्रैक्ट्स",
"contracts.searchPlaceholder": "किसान का नाम, कॉन्ट्रैक्ट आईडी या फसल के प्रकार से खोजें...",
"contracts.allStatus": "सभी स्थिति",
"contracts.active": "सक्रिय",
"contracts.pendingFarmerSignature": "किसान के हस्ताक्षर लंबित",
"contracts.completed": "पूर्ण",
"contracts.cancelled": "रद्द",
"contracts.loadError": "कॉन्ट्रैक्ट्स लोड करने में असमर्थ।",
"contracts.loading": "कॉन्ट्रैक्ट्स लोड हो रहे हैं...",
"contracts.farmer": "किसान",
"contracts.awaitingFarmerSign": "किसान के हस्ताक्षर की प्रतीक्षा",
"contracts.activeAndGrowing": "सक्रिय और फसल उग रही है",
"contracts.delivered": "डिलीवर किया गया",
"contracts.pending": "लंबित",
"contracts.unknownLocation": "अज्ञात स्थान",
"contracts.crop": "फसल",
"contracts.farmerPartner": "किसान साझेदार",
"contracts.cropTypeAndVolume": "फसल का प्रकार और मात्रा",
"contracts.locked": "निश्चित मात्रा",
"contracts.pricePerKg": "प्रति किलोग्राम कीमत",
"contracts.totalSettlementValue": "कुल निपटान मूल्य",
"contracts.status": "स्थिति",
"contracts.manageContract": "कॉन्ट्रैक्ट मैनेज करें",
"contracts.noMatch": "आपके फ़िल्टर से मेल खाने वाला कोई कॉन्ट्रैक्ट नहीं मिला।",
"contracts.adjustSearch": "अपनी खोज या स्थिति फ़िल्टर को बदलकर देखें।",
"contracts.showing": "दिखाए जा रहे हैं",
"contracts.of": "में से",
"contracts.contracts": "कॉन्ट्रैक्ट्स",

"buyerDashboard.dashboard": "डैशबोर्ड",
"buyerDashboard.postRequirement": "आवश्यकता पोस्ट करें",
"buyerDashboard.myRequirements": "मेरी आवश्यकताएँ",
"buyerDashboard.myContracts": "मेरे कॉन्ट्रैक्ट्स",
"buyerDashboard.activeOrders": "सक्रिय ऑर्डर्स",
"buyerDashboard.connectedFarmers": "जुड़े हुए किसान",
"buyerDashboard.analytics": "एनालिटिक्स",
"buyerDashboard.messages": "मैसेजेस",
"buyerDashboard.profile": "प्रोफ़ाइल",
"buyerDashboard.logout": "लॉगआउट",
"buyerDashboard.postedRequirements": "पोस्ट की गई आवश्यकताएँ",
"buyerDashboard.postedRequirementsSubtitle": "आपकी वर्तमान खरीद आवश्यकताएँ",
"buyerDashboard.pendingFarmerRequests": "किसानों के लंबित अनुरोध",
"buyerDashboard.pendingFarmerRequestsSubtitle": "किसानों के जवाब की प्रतीक्षा",
"buyerDashboard.activeContracts": "सक्रिय कॉन्ट्रैक्ट्स",
"buyerDashboard.activeContractsSubtitle": "प्रगति पर चल रहे कॉन्ट्रैक्ट्स",
"buyerDashboard.completedContracts": "पूर्ण कॉन्ट्रैक्ट्स",
"buyerDashboard.completedContractsSubtitle": "सफलतापूर्वक पूरे किए गए सौदे",
"buyerDashboard.totalSpending": "कुल खर्च",
"buyerDashboard.totalSpendingSubtitle": "निपटाए गए खरीद का मूल्य",
"buyerDashboard.loading": "लोड हो रहा है...",
"buyerDashboard.error": "डैशबोर्ड डेटा लोड करने में असमर्थ।",
"buyerDashboard.title": "खरीदार डैशबोर्ड",
"buyerDashboard.welcome": "वापसी पर स्वागत है, FreshMart 👋",
"buyerDashboard.description": "अपनी कृषि खरीद प्रक्रिया को आसान बनाएँ। सत्यापित किसानों से सीधे जुड़ने और कॉन्ट्रैक्ट बनाने के लिए हमारे AI टूल्स का उपयोग करें।",
"buyerDashboard.aiFarmerMatching": "AI किसान मिलान",
"buyerDashboard.smartEngine": "स्मार्ट इंजन",
"buyerDashboard.matchingDescription": "हमारा स्मार्ट मैचमेकिंग एल्गोरिदम आपकी फसल की आवश्यकताओं को सत्यापित किसानों के साथ तुरंत मिलाता है।",
"buyerDashboard.findMatches": "मैच खोजें",
"buyerDashboard.instantMetricsMatch": "तुरंत मेट्रिक्स मिलान",
"buyerDashboard.instantMetricsDescription": "सक्रिय फसल अवधि, स्थान की निकटता और माँगी गई फसल की किस्मों के आधार पर किसानों को स्वचालित रूप से फ़िल्टर करता है।",
"buyerDashboard.trustScoreEvaluation": "ट्रस्ट स्कोर मूल्यांकन",
"buyerDashboard.trustScoreDescription": "खरीद जोखिम कम करने के लिए सत्यापित इतिहास, मूल्य विश्वसनीयता और पिछले ऑर्डर्स की पूर्ति दर के आधार पर किसानों की रैंकिंग करता है।",
"buyerDashboard.optimizedNegotiations": "अनुकूलित बातचीत",
"buyerDashboard.optimizedNegotiationsDescription": "स्थानीय मंडी की वास्तविक समय की कीमतों और मात्रा के आधार पर बुद्धिमान शुरुआती मूल्य सीमा प्रदान करता है।",
"buyerDashboard.logoutConfirmation": "क्या आप वाकई लॉगआउट करना चाहते हैं?",
"buyerDashboard.logoutDescription": "अपने डैशबोर्ड पैनल तक पहुँचने के लिए आपको फिर से अपनी जानकारी दर्ज करनी होगी।",
"buyerDashboard.cancel": "रद्द करें",
"buyerDashboard.yesLogout": "हाँ, लॉगआउट करें",

"farmerProfile.back": "वापस",
"farmerProfile.notFound": "किसान नहीं मिला",
"farmerProfile.verifiedFarmer": "सत्यापित किसान",
"farmerProfile.land": "भूमि",
"farmerProfile.water": "पानी",
"farmerProfile.expectedYield": "अपेक्षित उपज",
"farmerProfile.trustScore": "ट्रस्ट स्कोर",
"farmerProfile.sendRequirementRequest": "आवश्यकता अनुरोध भेजें",

"buyerLogin.backToHome": "होम पर वापस जाएँ",
"buyerLogin.joinAsBuyer": "KrishiSetu पर खरीदार के रूप में जुड़ें",
"buyerLogin.welcomeBack": "वापसी पर स्वागत है, खरीदार",
"buyerLogin.registerDescription": "किसानों से सीधे खरीदारी शुरू करने के लिए अपना अकाउंट बनाएँ",
"buyerLogin.loginDescription": "अपने मार्केटप्लेस और ऑर्डर्स तक पहुँचने के लिए साइन इन करें",
"buyerLogin.login": "लॉगिन",
"buyerLogin.register": "रजिस्टर करें",
"buyerLogin.fullName": "पूरा नाम",
"buyerLogin.enterFullName": "अपना पूरा नाम दर्ज करें",
"buyerLogin.phoneNumber": "फ़ोन नंबर",
"buyerLogin.enterPhone": "10 अंकों का नंबर दर्ज करें",
"buyerLogin.password": "पासवर्ड",
"buyerLogin.companyName": "कंपनी का नाम (वैकल्पिक)",
"buyerLogin.businessName": "व्यवसाय का नाम",
"buyerLogin.completeRegistration": "रजिस्ट्रेशन पूरा करें",
"buyerLogin.signIn": "साइन इन करें",
"buyerLogin.secureTrade": "सुरक्षित व्यापार",
"buyerLogin.verifiedUsers": "सत्यापित उपयोगकर्ता",
"buyerLogin.registrationSuccess": "खरीदार रजिस्ट्रेशन सफल रहा!",
"buyerLogin.registrationFailed": "रजिस्ट्रेशन असफल रहा।",
"buyerLogin.loginSuccess": "लॉगिन सफल रहा!",
"buyerLogin.loginFailed": "लॉगिन असफल रहा।",
"buyerLogin.somethingWentWrong": "कुछ गलत हो गया!",

"buyerMessages.backToDashboard": "डैशबोर्ड पर वापस जाएँ",
"buyerMessages.growerNetworks": "किसान नेटवर्क",
"buyerMessages.searchFarmers": "किसानों को खोजें...",
"buyerMessages.trustScore": "विश्वास स्कोर",
"buyerMessages.typeMessage": "संदेश लिखें...",
"buyerMessages.typeYourMessage": "अपना संदेश लिखें...",
"buyerMessages.verified": "सत्यापित",

"myRequirements.backToDashboard": "डैशबोर्ड पर वापस जाएं",
"myRequirements.title": "मेरी पोस्ट की गई आवश्यकताएं",
"myRequirements.subtitle": "अपनी सभी सक्रिय फसल आवश्यकताओं और खरीद मांगों को देखें।",
"myRequirements.loading": "आपकी आवश्यकताएं लोड हो रही हैं...",
"myRequirements.loadErrorTitle": "आवश्यकताएं लोड नहीं हो सकीं",
"myRequirements.noRequirementsTitle": "अभी तक कोई आवश्यकता पोस्ट नहीं की गई",
"myRequirements.noRequirementsDescription": "आपके अकाउंट के लिए वर्तमान में कोई आवश्यकता नहीं मिली।",
"myRequirements.active": "सक्रिय",
"myRequirements.quantity": "मात्रा",
"myRequirements.targetPrice": "लक्षित कीमत",
"myRequirements.deadline": "अंतिम तिथि",
"myRequirements.na": "उपलब्ध नहीं",
"myRequirements.unableToLoad": "आपकी आवश्यकताएं लोड नहीं हो सकीं। कृपया पुनः प्रयास करें।",

"notifications.title": "सूचनाएं",
"notifications.subtitle": "अपनी KrishiSetu गतिविधियों से अपडेट रहें।",
"notifications.markAllAsRead": "सभी को पढ़ा हुआ चिन्हित करें",
"notifications.loading": "सूचनाएं लोड हो रही हैं...",
"notifications.error": "सूचनाएं लोड नहीं हो सकीं।",
"notifications.new": "नई",
"notifications.viewDetails": "विवरण देखें →",
"notifications.noNotifications": "अभी तक कोई सूचना नहीं है।",

buyerAIInsightsTitle: "AI बाज़ार जानकारी",
buyerAIInsightsSubtitle:
  "KrishiSetu AI द्वारा संचालित व्यक्तिगत सुझाव",
highDemandAlert: "उच्च मांग की चेतावनी",
wheatDemandIncrease:
  "अगले 30 दिनों में गेहूं की मांग 18% बढ़ने की उम्मीद है।",
pricePrediction: "कीमत का अनुमान",
tomatoPriceIncrease:
  "कम उत्पादन की उम्मीद के कारण टमाटर की कीमतें बढ़ सकती हैं।",
bestProcurementTime: "खरीदारी का सबसे अच्छा समय",
bookContracts:
  "बेहतर कीमतों के लिए अगले 7 दिनों के भीतर अनुबंध बुक करें।",

  buyerInformation: "खरीदार की जानकारी",
fullName: "पूरा नाम",
email: "ईमेल",
phoneNumber: "फ़ोन नंबर",
location: "स्थान",
companyDetails: "कंपनी का विवरण",
optional: "वैकल्पिक",
companyName: "कंपनी का नाम",
businessType: "व्यवसाय का प्रकार",
gstNumber: "GST नंबर",
companyAddress: "कंपनी का पता",
notAvailable: "उपलब्ध नहीं",
noCompanyAdded: "कोई कंपनी नहीं जोड़ी गई",
individualBuyerMessage:
  "यह खरीदार एक व्यक्तिगत खरीदार के रूप में पंजीकृत है।",

  buyer: "खरीदार",
changePhoto: "फ़ोटो बदलें",
verifiedBuyer: "सत्यापित खरीदार",
gst: "GST",
address: "पता",
editProfile: "प्रोफ़ाइल संपादित करें",
memberSince: "सदस्य बनने की तारीख",
buyerType: "खरीदार का प्रकार",
completedOrders: "पूरे किए गए ऑर्डर",
trustScore: "विश्वास स्कोर",
outOf100: "100 में से",
trustedByVerifiedFarmers:
  "KrishiSetu पर सत्यापित किसानों द्वारा भरोसेमंद",
platinumTrustedBuyer: "💎 प्लैटिनम विश्वसनीय खरीदार",
goldTrustedBuyer: "🏅 गोल्ड विश्वसनीय खरीदार",
silverTrustedBuyer: "🥈 सिल्वर विश्वसनीय खरीदार",
bronzeTrustedBuyer: "🥉 ब्रॉन्ज़ विश्वसनीय खरीदार",

purchaseHistory: "खरीद इतिहास",
recentProcurementRecords: "हालिया खरीद रिकॉर्ड",
farmer: "किसान",
quantity: "मात्रा",
delivered: "डिलीवर किया गया",
completed: "पूरा हुआ",

currentBuyingRequirements: "वर्तमान खरीद आवश्यकताएँ",
activeRecords: "सक्रिय रिकॉर्ड",
loadingRequirements: "आवश्यकताएँ लोड हो रही हैं...",
couldNotLoadRequirements: "आवश्यकताएँ लोड नहीं की जा सकीं।",
noRequirementsFound: "कोई आवश्यकता नहीं मिली।",
unknownCrop: "अज्ञात फसल",
unknownLocation: "अज्ञात स्थान",
priceNotSet: "कीमत निर्धारित नहीं है",
noDeadlineSet: "कोई अंतिम तिथि निर्धारित नहीं है",
active: "सक्रिय",
cancelled: "रद्द",

farmerReviews: "किसानों की समीक्षाएँ",
paymentReleasedOnTime: "भुगतान समय पर जारी किया गया। बहुत ही पेशेवर खरीदार।",
communicationWasSmooth: "बातचीत अच्छी रही और अनुबंध प्रक्रिया पारदर्शी थी।",
highlyRecommended: "अत्यधिक अनुशंसित। गुणवत्ता सत्यापन निष्पक्ष और तेज़ था।",

connectedFarmers: "जुड़े हुए किसान",
activeRequirements: "सक्रिय आवश्यकताएँ",
averageRating: "औसत रेटिंग",

backToDashboard: "डैशबोर्ड पर वापस जाएं",
loadingProfile: "प्रोफ़ाइल लोड हो रही है...",
loadProfile: "प्रोफ़ाइल लोड नहीं हो सकी",
updateProfile: "प्रोफ़ाइल अपडेट नहीं हो सकी",

"farmerRequest.back": "वापस जाएं",
"farmerRequest.farmerNotFound": "किसान नहीं मिला",
"farmerRequest.title": "किसान अनुरोध",
"farmerRequest.subtitle": "किसान को सहयोग अनुरोध भेजें",
"farmerRequest.selectedFarmer": "चयनित किसान",
"farmerRequest.trustScore": "विश्वास स्कोर",
"farmerRequest.contractFarmingRequest": "अनुबंध खेती अनुरोध",
"farmerRequest.requestDescription":
  "आपकी फसल की आवश्यकता का अनुरोध इस किसान को भेजा जाएगा। किसान अनुरोध को स्वीकार या अस्वीकार कर सकता है।",
"farmerRequest.sendRequest": "अनुरोध भेजें",
"farmerRequest.requestSentSuccessfully":
  "किसान को अनुरोध सफलतापूर्वक भेज दिया गया!",
  
  "buyerSettings.backToDashboard": "डैशबोर्ड पर वापस जाएं",
"buyerSettings.title": "खरीदार खाता सेटिंग्स",
"buyerSettings.subtitle": "कॉर्पोरेट जानकारी, GST विवरण, सुरक्षा और इनवॉइस प्राथमिकताओं को प्रबंधित करें।",

"buyerSettings.tabs.accountPassword": "खाता और पासवर्ड",
"buyerSettings.tabs.taxBusinessKyc": "टैक्स और बिज़नेस KYC",
"buyerSettings.tabs.procurementAlerts": "खरीदारी अलर्ट",
"buyerSettings.tabs.dangerZone": "खाता डेंजर ज़ोन",

"buyerSettings.security.title": "सुरक्षा और लॉगिन विवरण",
"buyerSettings.security.description": "पासवर्ड और प्राथमिक संपर्क ईमेल प्रबंधित करें।",
"buyerSettings.security.officialWorkEmail": "आधिकारिक कार्य ईमेल",
"buyerSettings.security.currentPassword": "वर्तमान पासवर्ड",
"buyerSettings.security.newPassword": "नया पासवर्ड",
"buyerSettings.security.newPasswordPlaceholder": "नया मजबूत पासवर्ड दर्ज करें",
"buyerSettings.security.saveChanges": "सुरक्षा बदलाव सेव करें",

"buyerSettings.business.title": "बिज़नेस सत्यापन और GST",
"buyerSettings.business.description": "ऑटोमेटेड इनवॉइसिंग के लिए कंपनी की टैक्स पहचान अपडेट करें।",
"buyerSettings.business.gstinNumber": "GSTIN नंबर",
"buyerSettings.business.tradeLicense": "कंपनी ट्रेड लाइसेंस नंबर",
"buyerSettings.business.updateTaxInfo": "टैक्स जानकारी अपडेट करें",

"buyerSettings.notifications.title": "खरीदारी अलर्ट",
"buyerSettings.notifications.description": "सोर्सिंग के लिए ईमेल और ऑर्डर नोटिफिकेशन कॉन्फ़िगर करें।",
"buyerSettings.notifications.farmerMatchTitle": "नए किसान मैच अलर्ट 🌱",
"buyerSettings.notifications.farmerMatchDescription": "जब किसान आपकी सक्रिय खरीदारी आवश्यकताओं से मेल खाने वाली फसल लिस्टिंग पोस्ट करें, तो सूचना प्राप्त करें।",
"buyerSettings.notifications.contractTitle": "कॉन्ट्रैक्ट स्वीकृति और PDF पुष्टि 📑",
"buyerSettings.notifications.contractDescription": "किसान द्वारा आपके ऑफ़र पर हस्ताक्षर या स्वीकृति देने के तुरंत बाद कॉन्ट्रैक्ट की कॉपी प्राप्त करें।",
"buyerSettings.notifications.weeklyDigestTitle": "साप्ताहिक मार्केट सोर्सिंग डाइजेस्ट",
"buyerSettings.notifications.weeklyDigestDescription": "अपने लक्षित क्षेत्रों में नई लिस्ट की गई फसलों की साप्ताहिक जानकारी ईमेल के माध्यम से प्राप्त करें।",

"buyerSettings.danger.title": "खाता डेंजर ज़ोन",
"buyerSettings.danger.description": "कॉर्पोरेट खाते की स्थिति प्रबंधित करें।",
"buyerSettings.danger.deactivateTitle": "कॉर्पोरेट खरीदार खाता निष्क्रिय करें",
"buyerSettings.danger.deactivateDescription": "खाता निष्क्रिय करने से सभी सक्रिय खरीदारी अनुरोध रुक जाएंगे और आपकी लिस्टिंग किसान मैचिंग फीड से हटा दी जाएगी।",
"buyerSettings.danger.deactivateAccount": "खाता निष्क्रिय करें",

"buyerLayout.goToHomepage": "होमपेज पर जाएं",
"buyerLayout.searchPlaceholder": "किसानों, फसलों, कॉन्ट्रैक्ट्स को खोजें...",
"buyerLayout.postRequirement": "आवश्यकता पोस्ट करें",
"buyerLayout.post": "पोस्ट करें",
"buyerLayout.notifications": "सूचनाएं",
"buyerLayout.buyerProfile": "खरीदार प्रोफ़ाइल",
"buyerLayout.verifiedBuyer": "सत्यापित खरीदार",
"buyerLayout.myProfile": "मेरी प्रोफ़ाइल",
"buyerLayout.accountSettings": "अकाउंट सेटिंग्स",

 },
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export function LanguageProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language | null;

    if (savedLanguage === "en" || savedLanguage === "hi") {
      setLanguageState(savedLanguage);
    }
  }, []);


  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem("language", newLanguage);
  };

const t = (key: string) => {
  return translations[language][key as keyof typeof translations[typeof language]] || key;
};

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }

  return context;
}